language: go

go:
  - 1.15.x

env:
  - GO111MODULE=on

git:
  depth: 1
  submodules: false

go_import_path: code.cloudfoundry.org/eirini

# Install dependencies responsible for testing/linting
before_install:
    - go get github.com/onsi/ginkgo/ginkgo
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin

# Skip install step; use vendored dependencies
install: true

script:
    - go vet -mod=vendor ./...
    - scripts/run_unit_tests.sh
    - golangci-lint run -v
