---
apiVersion: batch/v1
kind: Job
metadata:
  name: eirini-test
  namespace: eirini-test
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        name: eirini-test
    spec:
      serviceAccountName: eirini-integration-tests
      containers:
      - name: tests
        image: eirini/ci
        env:
        - name: WORK_DIR
          value: "/workspace"
        envFrom:
        - secretRef:
            name: test-secret
        - configMapRef:
            name: test-config
        command:
        - /bin/bash
        - -c
        - |
            set -ex

            EIRINI_DIR="$WORK_DIR/eirini"
            EIRINI_COMMIT=${EIRINI_COMMIT:-"HEAD"}

            mkdir -p "$WORK_DIR"

            if [ -d "/eirini" ]; then
              cp -a /eirini "$WORK_DIR"
            else
              git clone https://github.com/cloudfoundry-incubator/eirini.git "$EIRINI_DIR"
            fi

            pushd "$EIRINI_DIR"
            {
              git checkout "$EIRINI_COMMIT"
              $TEST_SCRIPT
            }
            popd
        volumeMounts:
        # - name: eirini-code
        #   mountPath: /eirini
        - name: go-cache
          mountPath: /root/.cache/go-build
      restartPolicy: Never
      volumes:
      # - name: eirini-code
      #   hostPath:
      #     path: /eirini
      #     type: Directory
      - name: go-cache
        persistentVolumeClaim:
          claimName: go-cache
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eirini-integration-tests
  namespace: eirini-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: make-cluster-admin
  namespace: eirini-test
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-integration-tests
  namespace: eirini-test

